/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_melp_v8_V8 */

#ifndef _Included_nl_melp_v8_V8
#define _Included_nl_melp_v8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_melp_v8_V8
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_melp_v8_V8_run
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
