/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_melp_v8_V8 */

#ifndef _Included_nl_melp_v8_V8
#define _Included_nl_melp_v8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_melp_v8_V8
 * Method:    createContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_nl_melp_v8_V8_createContext
  (JNIEnv *, jobject);

/*
 * Class:     nl_melp_v8_V8
 * Method:    disposeContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_nl_melp_v8_V8_disposeContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_melp_v8_V8
 * Method:    createIsolate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_nl_melp_v8_V8_createIsolate
  (JNIEnv *, jobject, jint);

/*
 * Class:     nl_melp_v8_V8
 * Method:    disposeIsolate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_nl_melp_v8_V8_disposeIsolate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     nl_melp_v8_V8
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_melp_v8_V8_sayHello__
  (JNIEnv *, jobject);

/*
 * Class:     nl_melp_v8_V8
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nl_melp_v8_V8_sayHello__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
